### ISSUE TITLE
Only allow certain routes

### ISSUE THREAD

**Issue by AnthonyHewins** [mstgnz/go-minio-cdn#2]
I have a need to only allow `GET`s, I'm going to create a PR to accomplish that. I have a preference of the flag library to use so if you want just the standard library let me know

**Comment by mstgnz** [comment]
This CDN project is used in the company where I work. The company has multiple projects, and when I joined, each project had its own static files. I developed a CDN service to centralize this, removing the burden from all projects. Currently, this project holds terabytes of data and also performs backups to AWS S3 Glacier.

I would like to further enhance this project and write tests, but unfortunately, I don't have free time.

If you like this project and would like to contribute, I would greatly appreciate it.

Due to the CDN service logic, there are no restrictions on GET requests only; however, other requests should undergo token verification.

I am personally against over-dependency in a project, if the language itself can handle the development, I find the external package unnecessary. Of course, if the external package is more performant and easier to write than the standard library, then it can be used.
