### ISSUE TITLE
Still error Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by yagi339** [mstgnz/go-minio-cdn#7]
<img width="574" alt="Screenshot 2024-09-17 at 03 26 40" src="https://github.com/user-attachments/assets/f3036587-7559-4fca-954b-1ea395045565">
i am 
<img width="566" alt="Screenshot 2024-09-17 at 03 26 10" src="https://github.com/user-attachments/assets/71168d4a-3815-44f2-ad80-f95cb0443596">
comment comment out that 
logging
    driver: none
but still error Still error Fatal glibc error: CPU does not support x86-64-v2
Could u verify it again?

**Comment by mstgnz** [comment]
this error is not caused by this application. It is caused by your CPU. These are the results when I searched for your error.

[results for CPU error](https://www.google.com/search?q=CPU+does+not+support+x86-64-v2&oq=CPU+does+not+support+x86-64-v2&gs_lcrp=EgZjaHJvbWUyCwgAEEUYExg5GIAEMgkIARAAGBMYgAQyCQgCEAAYExiABDIJCAMQABgTGIAEMgkIBBAAGBMYgAQyBggFEEUYPDIGCAYQRRg9MgYIBxBFGD3SAQcyODNqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8)

[results for CPU error with docker](https://www.google.com/search?q=docker+CPU+does+not+support+x86-64-v2&sca_esv=ed538c964041f2cb&sca_upv=1&sxsrf=ADLYWIJqex2Br8XzwINA6VvVkgPfq5ENJA%3A1726568147010&ei=01bpZqIkxYvs1g_Lo-mRDA&ved=0ahUKEwji2dTI38mIAxXFBdsEHctROsIQ4dUDCA8&uact=5&oq=docker+CPU+does+not+support+x86-64-v2&gs_lp=Egxnd3Mtd2l6LXNlcnAiJWRvY2tlciBDUFUgZG9lcyBub3Qgc3VwcG9ydCB4ODYtNjQtdjIyBhAAGAcYHjIGEAAYBxgeMggQABiABBjLATIGEAAYBRgeMggQABiABBiiBEiLTFD0BFiYSHAPeAGQAQCYAZkBoAHPDqoBBDAuMTW4AQPIAQD4AQGYAhegAvoHwgIKEAAYsAMY1gQYR8ICDRAAGIAEGLADGEMYigXCAggQABgFGAcYHsICCBAAGBMYBxgewgIKEAAYExgFGAcYHsICChAAGBMYBRgNGB7CAgkQABiABBgTGA3CAgoQABgTGAgYDRgemAMAiAYBkAYJkgcEMTUuOKAH60U&sclient=gws-wiz-serp)

you also need to rebuild `docker-compose up -d --build`

**Comment by yagi339** [comment]
I am tried 2 server one from google cloud and one from this atlantic https://www.atlantic.net/vps-hosting/ and fresh server but not success. Could you verify and build a new docker?

**Comment by mstgnz** [comment]
The imagick version has been updated, can you clone the latest version of the repo and run it again with the logging comment in the docker-compose.yaml file? `docker-compose up -d --build`
